version: '2'

services:
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9443:9443"
      - "8000:8000"
    command: --admin-password "${PASS_POR}"
    networks:
      - por_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

networks:
  por_net:
    driver: bridge

volumes:
  portainer_data:
